name: Cog Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # permet de lancer à la main depuis l’onglet Actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: replicate/setup-cog@v2
        with:
          install-cuda: true
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push model image to r8.im
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}
        run:  |
          cog push r8.im/alexandra1610/sam-vit-h-box
