name: Cog Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04   # <--- plus stable que ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog
        run: curl -fsSL https://cog.run/install.sh | sudo sh

      - name: Login to Replicate
        run: cog login --token ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push model image to r8.im
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}
        run: cog push r8.im/alexandra1610/sam-vit-h-box
