name: Cog Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04   # <--- plus stable que ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog
        run: |
          curl -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64.tar.gz -o cog.tar.gz
          tar -xzf cog.tar.gz
          sudo mv cog /usr/local/bin/



      - name: Login to Replicate
        run: cog login --token ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push model image to r8.im
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}
        run: cog push r8.im/alexandra1610/sam-vit-h-box
